/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "black-1": "var(--black-1)",
        blue: "var(--blue)",
        "gray-paragraph": "var(--gray-paragraph)",
        grey: "var(--grey)",
        "grey-dark": "var(--grey-dark)",
        "light-background": "var(--light-background)",
        "light-background-color": "var(--light-background-color)",
        "light-gray-1": "var(--light-gray-1)",
        "light-text-color": "var(--light-text-color)",
        "main-blue": "var(--main-blue)",
        "main-green": "var(--main-green)",
        "main-red": "var(--main-red)",
        navy: "var(--navy)",
        red: "var(--red)",
        "rose-code": "var(--rose-code)",
        "second-text-color": "var(--second-text-color)",
        "text-clr": "var(--text-clr)",
        "text-color": "var(--text-color)",
        violet: "var(--violet)",
        white: "var(--white)",
        "x-1st": "var(--x-1st)",
      },
      fontFamily: {
        "12pt-medium": "var(--12pt-medium-font-family)",
        "12pt-reguler": "var(--12pt-reguler-font-family)",
        "14pt-medium": "var(--14pt-medium-font-family)",
        "16pt-medium": "var(--16pt-medium-font-family)",
        "16pt-reg": "var(--16pt-reg-font-family)",
        "22pt-medium": "var(--22pt-medium-font-family)",
        "22pt-reg": "var(--22pt-reg-font-family)",
        "24pt-medium": "var(--24pt-medium-font-family)",
        "btn-text": "var(--btn-text-font-family)",
        "h-2": "var(--h-2-font-family)",
        "h-5": "var(--h-5-font-family)",
        "h-6": "var(--h-6-font-family)",
        "h6-20px": "var(--h6-20px-font-family)",
        "h7-16px-paragraph-text": "var(--h7-16px-paragraph-text-font-family)",
        "josefin-16": "var(--josefin-16-font-family)",
        link: "var(--link-font-family)",
        paragraph: "var(--paragraph-font-family)",
      },
      boxShadow: {
        "effect-1": "var(--effect-1)",
        "shadow-style-1": "var(--shadow-style-1)",
        "shadow-style-2": "var(--shadow-style-2)",
        "shadow-style-3": "var(--shadow-style-3)",
        "shadow-style-4-UP": "var(--shadow-style-4-UP)",
      },
    },
  },
  plugins: [],
};
